services:
  app_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: maycon_user
      POSTGRES_DB: maycon_db
      POSTGRES_PASSWORD: maycon_password
    ports:
      - "5432:5432"

  app:
    image: fastapi_app
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - app_database
    environment:
      DATABASE_URL: postgresql+psycopg://maycon_user:maycon_password@app_database:5432/maycon_db

volumes:
  pgdata: